config/routes.rb
Rails.application.routes.draw do
  get '/' => 'top#top'
  get 'top/serch' => 'top#serch'
  get 'top/serchtag' => 'top#serchtag'
  resources :posts
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :tags
    has_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :posts
    belongs_to :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable  :registerable,
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	private
	def sign_in_required
		redirect_to new_user_session_url unless user_signed_in?
	end
end

app/controllers/posts_controller.rb
require "net/http"

class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :sign_in_required, only: [:new, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(updated_at: :asc) 
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :tags, :public, :movetag, :image, :image_out_url)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def top
    @posts = Post.all
  end
  def serch
    @noresult = '検索結果はありません'
    key = "pSCglKF5uFWoSzJvPCcI"
    #url =  "https://api.mozambiquehe.re/bridge?version=4&platform=PC&player=#{params[:username]}&auth=#{key}"
    url =  "https://api.mozambiquehe.re/bridge?platform=PC&player=#{params[:username]}&auth=#{key}"
    begin
      url
      uri = URI.parse(url)
      uri = URI.parse(url)
      json = Net::HTTP.get(uri)
      @result = JSON.parse(json)
    rescue => exception
      @noresult
    end


  end
  def serchtag

    @posts = Post.where(tags: params[:tag])
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>タンク郎tube</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  </head>
  <style>
    body { 
      word-break: break-all;
      line-height: 1.1;
    }
    .card {
    position: relative;
    z-index: 1; /* 必要であればリンク要素の重なりのベース順序指定 */
    }
    .card a {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        text-indent:-999px;
        z-index: 2; /* 必要であればリンク要素の重なりのベース順序指定 */
    }
    a:hover{
    background-color:#6660;
    }
    .card-body {
    flex: 1 1 auto;
    padding: 0.6rem;
    }
    .col-xl, .col-xl-auto, .col-xl-12, .col-xl-11, .col-xl-10, .col-xl-9, .col-xl-8, .col-xl-7, .col-xl-6, .col-xl-5, .col-xl-4, .col-xl-3, .col-xl-2, .col-xl-1, .col-lg, .col-lg-auto, .col-lg-12, .col-lg-11, .col-lg-10, .col-lg-9, .col-lg-8, .col-lg-7, .col-lg-6, .col-lg-5, .col-lg-4, .col-lg-3, .col-lg-2, .col-lg-1, .col-md, .col-md-auto, .col-md-12, .col-md-11, .col-md-10, .col-md-9, .col-md-8, .col-md-7, .col-md-6, .col-md-5, .col-md-4, .col-md-3, .col-md-2, .col-md-1, .col-sm, .col-sm-auto, .col-sm-12, .col-sm-11, .col-sm-10, .col-sm-9, .col-sm-8, .col-sm-7, .col-sm-6, .col-sm-5, .col-sm-4, .col-sm-3, .col-sm-2, .col-sm-1, .col, .col-auto, .col-12, .col-11, .col-10, .col-9, .col-8, .col-7, .col-6, .col-5, .col-4, .col-3, .col-2, .col-1 {
    position: relative;
    width: 100%;
    min-height: 1px;
    padding-right: 12px;
    padding-left: 12px;
    }
  </style>
  <body>
    <header>
      <nav>
        <div class="navbar navbar-expand navbar-dark bg-dark">
          <a href="/" class="navbar-brand">タンク郎tube</a>
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to '記事一覧', '/posts', {class: "nav-link"} %>
              </li>
              
              <% if current_user %>
                <li class="nav-item">
                  <%= link_to 'admin', '/admin', {class: "nav-link"} %>
                </li>
              <% end %>
            </ul>
            <%# <form class="form-inline my-2 my-md-0">
              <input class="form-control" type="text" placeholder="Search">
            </form>
             %>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br />
    <%= form.text_field :title %>
  </div>
<%= form.file_field :image %>
  <div class="field">
    <%= form.label :content %><br />
    <%= form.text_area :content, rows: 60, cols: 60 %>
  </div>

  <div class="field">
    <%= form.label :tags %><br />
    <%= form.text_field :tags %>
  </div>

  <div class="field">
    <%= form.label :image_url %><br />
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :公開 %><br />
    <%= form.check_box :public, id: :public,:as => :boolean%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<style>
  .thumbnail{
    position:relative;
    width:100%;
    height:0;
    padding-top:56%;
  }
  .thumbnail img{
      position:absolute;
      top:0;
      left:0;
      width:100%;
      height:100%;
  }
</style>

<p id="notice"><%= notice %></p>

<div class="row">
  <% @posts.each do |post| %>
    <% if post.public == true or current_user %>
      <div class="col-lg-6 pb-1">
        <div class="card shadow-sm">
          <div class="card-body">
            <div class="row">
              <div class="col-7">
                <div class="thumbnail">
                    <% if post.image_out_url %>
                    <img src="<%= post.image_out_url %>">
                  <% else %>
                    <%= image_tag post.image.to_s, class: 'image' %>
                  <% end %>
                </div>
              </div>
              <div class="col-5">
                <% if post.title.length < 40 %>
                  <div><%= post.title %></div>
                <% else %>
                  <div><%= post.title.truncate(40) %></div>
                <% end %>
                <% small_length = 40 - post.title.length %>
                <% if small_length > 0 %>
                  <small class="card-text text-muted"><%= post.content.truncate(small_length) %></small>
                <% end %>
                <div>
                  <small class="text-muted"><%= post.created_at.strftime("%Y-%m-%d") %></small>
                </div>
              </div>
            </div>
          </div>
          <%= link_to '', post %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<br>
<% if current_user %>
  <%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<style>
  .movie{
    position:relative;
    width:100%;
    height:0;
    padding-top:56%;
  }
  .movie iframe{
      position:absolute;
      top:0;
      left:0;
      width:100%;
      height:100%;
  }
</style>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-12">
    <div class="movie">
      <% if @post.movetag %>
        <div>
          <%= @post.movetag.html_safe %>
        </div>
      <% end %>
    </div>
    <div class="p-2">
      <div>
        <small><%= @post.tags %></small>
      </div> 
      <h4><%= @post.title %>
        <% if @post.public == false %>
          <small>非公開</small>
        <% end %>
      </h4>
      <div class="text-muted border-bottom">
        <span>
          <small><%= @post.created_at.strftime("%Y-%m-%d") %></small>
        </span>
      </div>
      <% if @post.content %>
        <div class="pt-2">
          <%= @post.content %>
        </div>
      <% end %>
      <%# image_tag @post.image.to_s , class: 'image' %>
      <div class="pt-3">
        <div>
          <% if current_user %>
            <%= link_to 'Edit', edit_post_path(@post) %>
          <% end %>
          <%= link_to '一覧に戻る', posts_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/top/serch.html.erb
  <% begin %>

    <%= @result["global"]["name"] %>
  <br>
    <%= @result["global"]["uid"] %>
  <br>
    <%= @result["global"]["avatar"] %>
  <br>
    <%= @result["global"]["platform"] %>
  <br>
    <%= @result["global"]["level"] %>
  <br>
    <%= @result["global"]["toMextLevelPercent"] %>
  <br>
    <%= @result["global"]["internalUpdateCount"] %>
  <br>
    <%= @result["global"]["rank"]["rankScore"] %>
  <br>
    <%= @result["global"]["rank"]["rankName"] %>
  <br>
    <%= @result["global"]["rank"]["rankDiv"] %>
  <br>
    <%= @result["global"]["rank"]["rankImg"] %>
  <br>  

  legends-selected
  <br>

    <%= @result["legends"]["selected"]["Lifeline"]["kills"] %>
  <br>  
     <%= @result["legends"]["selected"]["Lifeline"]["dropped_items_for_squadmates"] %>
  <br>  
     <%= @result["legends"]["selected"]["Lifeline"]["wins_season_4"] %>
  <br>  

  legends-all-Bangalore
  <br>
    <%= @result["legends"]["all"]["Bangalore"]["kills"] %>
  <br>  
    <%= @result["legends"]["all"]["Bangalore"]["creeping_barrage_damage"] %>
  <br>  
    <%= @result["legends"]["all"]["Bangalore"]["wins_season_1"] %>
  <br>  






  legends-all-bloodhound
  <br>
    <%= @result["legends"]["all"]["Bloodhound"]["kills"] %>
  <br>
    <%= @result["legends"]["all"]["Bloodhound"]["top_3"] %>
  <br>
    <%= @result["legends"]["all"]["Bloodhound"]["beast_of_the_hunt_kills"] %>
  <br>
    <%= @result["legends"]["all"]["Bloodhound"]["kills_season_4"] %>
  <br>

  legends-all-Lifeline
  <br>
    <%= @result["legends"]["all"]["Lifeline"]["kills"] %>
  <br>
    <%= @result["legends"]["all"]["Lifeline"]["damage"] %>
  <br>
    <%= @result["legends"]["all"]["Lifeline"]["games_played"] %>
  <br>
    <%= @result["legends"]["all"]["Lifeline"]["dropped_items_for_suquadmates"] %>
  <br>


    

  

  
  <% rescue => exception %>
    <%= @noresult%>
  <% end %>

app/views/top/serchtag.html.erb
<style>
  .thumbnail{
    position:relative;
    width:100%;
    height:0;
    padding-top:56%;
  }
  .thumbnail img{
      position:absolute;
      top:0;
      left:0;
      width:100%;
      height:100%;
  }
</style>

<p id="notice"><%= notice %></p>
  <div class="p-2">
  ユーザー検索
    <%= form_with(url: top_serchtag_path, method: :get, local: true, html:{class:"form-inline my-2 my-lg-0"},return_url: request.original_url) do |u| %>
      <%= u.text_field :tag, class:"form-control mr-sm-2", placeholder:"タグ" %>
      <div class="pr-3">
        <%= u.submit "検索", class:"btn btn-secondary my-2 my-sm-0" %>
      </div>
    <% end %>
</div>
<div class="row">
  <% @posts.each do |post| %>
    <% if post.public == true or current_user %>
      <div class="col-lg-6 pb-1">
        <div class="card shadow-sm">
          <div class="card-body">
            <div class="row">
              <>
              <div class="col-7">
                <div class="thumbnail">
                    <% if post.image_out_url %>
                    <img src="<%= post.image_out_url %>">
                  <% else %>
                    <%= image_tag post.image.to_s, class: 'image' %>
                  <% end %>
                </div>
              </div>
              <div class="col-5">
                <% if post.title.length < 40 %>
                  <div><%= post.title %></div>
                <% else %>
                  <div><%= post.title.truncate(40) %></div>
                <% end %>
                <% small_length = 40 - post.title.length %>
                <% if small_length > 0 %>
                  <small class="card-text text-muted"><%= post.content.truncate(small_length) %></small>
                <% end %>
                <div>
                  <small class="text-muted"><%= post.created_at.strftime("%Y-%m-%d") %></small>
                </div>
              </div>
            </div>
          </div>
          <%= link_to '', post %>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="p-2">

app/views/top/top.html.erb
<style>
  .thumbnail{
    position:relative;
    width:100%;
    height:0;
    padding-top:56%;
  }
  .thumbnail img{
      position:absolute;
      top:0;
      left:0;
      width:100%;
      height:100%;
  }
</style>

<p id="notice"><%= notice %></p>

<div class="row">
  <% @posts.each do |post| %>
    <% if post.public == true or current_user %>
      <div class="col-lg-6 pb-1">
        <div class="card shadow-sm">
          <div class="card-body">
            <div class="row">
              <>
              <div class="col-7">
                <div class="thumbnail">
                    <% if post.image_out_url %>
                    <img src="<%= post.image_out_url %>">
                  <% else %>
                    <%= image_tag post.image.to_s, class: 'image' %>
                  <% end %>
                </div>
              </div>
              <div class="col-5">
                <% if post.title.length < 40 %>
                  <div><%= post.title %></div>
                <% else %>
                  <div><%= post.title.truncate(40) %></div>
                <% end %>
                <% small_length = 40 - post.title.length %>
                <% if small_length > 0 %>
                  <small class="card-text text-muted"><%= post.content.truncate(small_length) %></small>
                <% end %>
                <div>
                  <small class="text-muted"><%= post.created_at.strftime("%Y-%m-%d") %></small>
                </div>
              </div>
            </div>
          </div>
          <%= link_to '', post %>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= @result %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>